CREATE TABLE IF NOT EXISTS t_clients
(
    t_client_id  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    t_firstname VARCHAR(255),
    t_lastname  VARCHAR(255),
    t_middlename VARCHAR(255)
);
