CREATE TABLE IF NOT EXISTS t_accounts
(
    t_account_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    t_client_id        BIGINT REFERENCES t_clients (t_client_id),
    t_account_number   INT UNIQUE NOT NULL,
    t_account_currency VARCHAR    NOT NULL
);

CREATE INDEX IF NOT EXISTS account_number_index ON t_accounts (t_account_number);
