CREATE TABLE IF NOT EXISTS t_operations
(
    t_operation_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    t_account_id     BIGINT REFERENCES t_accounts (t_account_id),
    t_timestamp      TIMESTAMP NOT NULL,
    t_payment_method VARCHAR   NOT NULL,
    t_sum            BIGINT    NOT NULL
);
