server:
  port: 8083

app:
  feign:
    client:
      config:
        cloud:
          url: "http://ebito-cloud-clusterip:8084"

spring:
  application:
    name: document-generator
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:9595
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
  security:
    user:
      name: client
      password: client
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: admin-server/src/main/resources/log/document_generator_api.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
