server:
  port: 8081

app:
  feign:
    client:
      config:
        cloud:
          url: "http://ebito-cloud-clusterip:8084"
        data-aggregator:
          url: "http://ebito-data-aggregator-clusterip:8082"
  connections:
    isAsyncConnectEnabled: false
  rabbitmq:
    queue: ebito_data_aggregator_req_q
    routingkey: ebito_data_aggregator_res_q
    exchange: ebito_exchange

spring:
  application:
    name: orchestrator
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:9595
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
  security:
    user:
      name: client
      password: client
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"